== Creating a Java Project for MicroProfile Development

=== Using Your IDE

Most modern IDEs have built-in support for creating Java and Maven projects. Depending on your chosen IDE, look for options like "New Project", or "New Maven Project" to get started. 
These options typically guide you through the setup process, including specifying the project's groupId, artifactId, and dependencies.

=== Using Maven from Command Line (Terminal)

For developers who prefer using the command line or for those setting up projects in environments without an IDE, Maven can generate the base structure of a Java project through its archetype mechanism. 
To create a project using Maven, open your terminal or command line and run the following command: 

[source, bash]
----
mvn archetype:generate -DgroupId=io.microprofile.tutorial -DartifactId=store -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
----

The above command creates a new Maven project based on the `maven-archetype-quickstart archetype`, setting the `groupId` as `io.microprofile.tutorial` and the `artifactID` as `store`. 

Next, using your file explorer or command line, create the following folder structure: 

[source, plain text]
----
.
├── pom.xml
├── readme.md
└── src
    └── main
    │   └── java
    │       └── io
    │           └── microprofile
    │               └── tutorial
    │                  └── store
    │                      └── product
    │                      │    ├── entity
    │                      │    │   └── Product.java
    │	                     │    └── service
    │                      │       └── ProductService.java
    │                      └── ProductRestApplication.java
    └── test
	      └── java
            └── io
                └── microprofile
                    └── tutorial
                       └── store
			                     └── product
                               └── ProductServiceTest.java
----

The heart of your Maven project is `pom.xml`. It defines project metadata, dependencies, and build configurations.
The content for the _pom.xml_ file should look as below, ensure MicroProfile depencency is added: 

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  
  <groupId>io.microprofile.tutorial</groupId>
  <artifactId>mp-ecomm</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>

  <!-- Setting the source and target of the Java Compiler !>
  <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
     <maven.compiler.source>17</maven.compiler.source>
     <maven.compiler.target>17</maven.compiler.target>             
  </properties>
...
...
   <!-- Add Lombok dependency -->
   <dependency>
     <groupId>org.projectlombok</groupId>
     <artifactId>lombok</artifactId>
     <version>1.18.26</version>
     <scope>provided</scope>
   </dependency>


   <!-- Adding Jakarta EE dependencies -->
   <dependency>
     <groupId>jakarta.platform</groupId>
     <artifactId>jakarta.jakartaee-api</artifactId>
     <version>10.0.0</version>
     <scope>provided</scope>
   </dependency>


   <!-- Adding MicroProfie dependency -->
   <dependency>
     <groupId>org.eclipse.microprofile</groupId>
     <artifactId>microprofile</artifactId>
     <version>6.1</version>
     <type>pom</type>
     <scope>provided</scope>
   </dependency>


   <!-- JUnit Jupiter API for writing tests -->
   <dependency>
       <groupId>org.junit.jupiter</groupId>
       <artifactId>junit-jupiter-api</artifactId>
       <version>5.8.2</version>
       <scope>test</scope>
   </dependency>
  
   <!-- JUnit Jupiter Engine for running tests -->
   <dependency>
       <groupId>org.junit.jupiter</groupId>
       <artifactId>junit-jupiter-engine</artifactId>
       <version>5.8.2</version>
       <scope>test</scope>
   </dependency>
...

----

Tip: Execute the `$ mvn validate command`. This checks the _pom.xml_ file for correctness, ensuring that all necessary configuration is present and valid. 
