== Testing your microservice

Testing is critical for ensuring the reliability and robustness of your microservice. Create a class called ProductResourceTest, which contains unit tests for the ProductService class as below:

[source, java]
----
package io.microprofile.tutorial.store.product.resource;


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;


import java.util.List;


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;


import io.microprofile.tutorial.store.product.entity.Product;


public class ProductResourceTest {
  private ProductResource productResource;


   @BeforeEach
   void setUp() {
       productResource = new ProductResource();
   }


   @AfterEach
   void tearDown() {
       productResource = null;
   }


   @Test
   void testGetProducts() {
       List<Product> products = productResource.getProducts();


       assertNotNull(products);
       assertEquals(2, products.size());
   }
}
----

Below are the assertions to test the `getProducts()` method of `ProductService`:

* The `assertNotNull(products)`; assertion checks that products are not `null`. It ensures the method returns a list, even if it’s empty. 
* The `assertEquals(2, products.size())`; assertion verifies that the list contains two products.

== Next Steps

Now that you have a basic MicroProfile service, consider exploring further:

* Adding configuration with MicroProfile Config
* Implementing health checks using MicroProfile Health
* Enhancing your service with MicroProfile Fault Tolerance

=== Resources
* MicroProfile Official Website: https://microprofile.io/
* MicroProfile GitHub Repository: https://github.com/eclipse/microprofile
* MicroProfile Documentation and Guides: [Official documentation](https://microprofile.io/documentation/)

After completing this chapter, you should have a basic understanding of MicroProfile and how to start building microservices with it. Continue exploring the specifications and capabilities of MicroProfile to fully leverage its power in your microservices architecture.
