name: Generate MicroProfile Tutorial

on:
  push:
    branches:
      - main  # Or your default branch

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version that matches your development environment

      - name: Install Antora
        run: npm install -g @antora/cli @antora/site-generator-default
      
      - name: Generate Site with Antora
        run: antora --fetch playbook.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site  # The default output directory for Antora
          publish_branch: gh-pages  # The target branch for GitHub Pages
